//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkDateRus.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehedule
    {
        public int Id { get; set; }
        public int WorkerId { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool Enabled { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
